name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set output variables
      id: vars
      run: |
        echo ::set-output name=tag::"$(date +%s)"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag apollon76/html2reader:${{ steps.vars.outputs.tag }} --tag apollon76/html2reader:latest
    
    - name: Login
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: docker login -u apollon76 -p "$DOCKER_HUB_PASSWORD"
      
    - name: Push
      run: |
        docker push apollon76/html2reader:${{ steps.vars.outputs.tag }}
        docker push apollon76/html2reader:latest
